// ============================================================
// 守护室 · 隐私仪表盘引擎（P15-6）
// 数据暴露面、权限审计、隐私评分、泄露预警、一键锁定
// ============================================================

import { ref, computed } from 'vue'
import { storage } from '../../engine/storage'
import type { ThreatLevel } from './incident-response'

// ============================================================
// 类型定义
// ============================================================

/** 数据类别 */
export type DataCategory =
  | 'emotion'        // 情绪数据
  | 'diary'          // 日记/笔记
  | 'personal'       // 个人信息
  | 'behavior'       // 行为记录
  | 'health'         // 健康数据
  | 'location'       // 位置数据
  | 'social'         // 社交数据
  | 'system'         // 系统配置
  | 'creative'       // 创作内容
  | 'financial'      // 财务数据

/** 敏感度级别 */
export type SensitivityLevel = 'public' | 'internal' | 'sensitive' | 'confidential' | 'critical'

/** 存储位置 */
export type StorageLocation = 'local' | 'encrypted_local' | 'session' | 'remote' | 'hybrid'

/** 暴露面状态 */
export type ExposureStatus = 'safe' | 'monitored' | 'exposed' | 'at_risk' | 'breached'

/** 数据暴露面条目 */
export interface DataExposure {
  /** 数据类别 */
  category: DataCategory
  /** 数据标签 */
  label: string
  /** 数据描述 */
  description: string
  /** 敏感度级别 */
  sensitivity: SensitivityLevel
  /** 存储位置 */
  storageLocation: StorageLocation
  /** 是否加密 */
  encrypted: boolean
  /** 估算数据量（条数） */
  estimatedCount: number
  /** 估算数据大小（字节） */
  estimatedSize: number
  /** 暴露面状态 */
  exposureStatus: ExposureStatus
  /** 访问次数（近30天） */
  recentAccessCount: number
  /** 最后访问时间 */
  lastAccessedAt: string | null
  /** 关联模块 */
  relatedModules: string[]
  /** 风险评分 0-100 */
  riskScore: number
}

/** 权限条目 */
export interface PermissionEntry {
  /** 权限 ID */
  id: string
  /** 权限名称 */
  name: string
  /** 权限描述 */
  description: string
  /** 关联模块 */
  module: string
  /** 关联数据类别 */
  dataCategories: DataCategory[]
  /** 权限级别 */
  level: 'read' | 'write' | 'admin' | 'full'
  /** 是否已授权 */
  granted: boolean
  /** 授权时间 */
  grantedAt: string | null
  /** 授权来源 */
  grantedBy: string
  /** 是否可撤销 */
  revocable: boolean
  /** 最后使用时间 */
  lastUsedAt: string | null
  /** 风险等级 */
  riskLevel: 'low' | 'medium' | 'high' | 'critical'
}

/** 权限审计报告 */
export interface PermissionAudit {
  /** 审计 ID */
  id: string
  /** 审计时间 */
  auditedAt: string
  /** 总权限数 */
  totalPermissions: number
  /** 已授权权限数 */
  grantedPermissions: number
  /** 高风险权限数 */
  highRiskPermissions: number
  /** 未使用权限数（超过30天） */
  unusedPermissions: number
  /** 过度授权数（权限级别超出实际需要） */
  overGrantedPermissions: number
  /** 权限条目列表 */
  permissions: PermissionEntry[]
  /** 审计建议 */
  recommendations: string[]
}

/** 隐私评分维度 */
export interface PrivacyScoreDimension {
  /** 维度名称 */
  name: string
  /** 得分 0-100 */
  score: number
  /** 权重 */
  weight: number
  /** 子项 */
  items: {
    label: string
    score: number
    maxScore: number
    status: 'pass' | 'warn' | 'fail'
  }[]
}

/** 隐私评分 */
export interface PrivacyScore {
  /** 总分 0-100 */
  total: number
  /** 评级 */
  grade: 'A' | 'B' | 'C' | 'D' | 'F'
  /** 各维度评分 */
  dimensions: PrivacyScoreDimension[]
  /** 评分时间 */
  scoredAt: string
  /** 趋势：相比上次评分的变化 */
  trend: 'improving' | 'stable' | 'declining'
  /** 变化量 */
  delta: number
}

/** 泄露预警 */
export interface LeakWarning {
  /** 预警 ID */
  id: string
  /** 预警级别 */
  level: ThreatLevel
  /** 预警标题 */
  title: string
  /** 预警描述 */
  description: string
  /** 涉及的数据类别 */
  affectedCategories: DataCategory[]
  /** 风险概率 0-1 */
  probability: number
  /** 影响范围 */
  impact: 'minimal' | 'moderate' | 'significant' | 'severe'
  /** 建议措施 */
  recommendations: string[]
  /** 预警时间 */
  warnedAt: string
  /** 是否已确认 */
  acknowledged: boolean
  /** 是否已解决 */
  resolved: boolean
  /** 自动生成 */
  autoGenerated: boolean
}

/** 锁定状态 */
export interface LockState {
  /** 是否已锁定 */
  locked: boolean
  /** 锁定时间 */
  lockedAt: string | null
  /** 锁定原因 */
  reason: string
  /** 锁定范围 */
  scope: 'all' | 'sensitive_only' | 'external_only'
  /** 锁定时长（分钟），0 表示手动解锁 */
  duration: number
  /** 锁定到期时间 */
  expiresAt: string | null
  /** 解锁方式 */
  unlockMethod: 'password' | 'biometric' | 'timeout' | 'manual'
  /** 锁定操作者 */
  lockedBy: string
}

/** 隐私仪表盘配置 */
export interface PrivacyDashboardConfig {
  /** 是否启用自动隐私评分 */
  autoScoring: boolean
  /** 自动评分间隔（天） */
  scoringInterval: number
  /** 是否启用泄露预警 */
  leakWarningEnabled: boolean
  /** 预警灵敏度 0-1 */
  warningSensitivity: number
  /** 一键锁定密码 */
  lockPassword?: string
  /** 自动锁定时间（分钟不活动后），0 禁用 */
  autoLockTimeout: number
  /** 是否启用权限审计 */
  permissionAuditEnabled: boolean
  /** 数据保留天数 */
  dataRetentionDays: number
}

// ============================================================
// 元数据
// ============================================================

/** 数据类别元数据 */
export const DATA_CATEGORY_META: Record<DataCategory, {
  label: string
  icon: string
  description: string
  defaultSensitivity: SensitivityLevel
}> = {
  emotion: { label: '情绪数据', icon: '🌸', description: '情绪记录、情绪波动历史', defaultSensitivity: 'sensitive' },
  diary: { label: '日记笔记', icon: '📝', description: '个人日记、反思笔记', defaultSensitivity: 'confidential' },
  personal: { label: '个人信息', icon: '👤', description: '姓名、生日、联系方式等', defaultSensitivity: 'confidential' },
  behavior: { label: '行为记录', icon: '📊', description: '操作日志、使用习惯', defaultSensitivity: 'internal' },
  health: { label: '健康数据', icon: '💚', description: '身心健康相关数据', defaultSensitivity: 'critical' },
  location: { label: '位置数据', icon: '📍', description: '地理位置、签到记录', defaultSensitivity: 'sensitive' },
  social: { label: '社交数据', icon: '👥', description: '社交互动、分享记录', defaultSensitivity: 'sensitive' },
  system: { label: '系统配置', icon: '⚙️', description: '应用设置、偏好配置', defaultSensitivity: 'internal' },
  creative: { label: '创作内容', icon: '🎨', description: '用户创作的作品', defaultSensitivity: 'sensitive' },
  financial: { label: '财务数据', icon: '💰', description: '交易记录、资产信息', defaultSensitivity: 'critical' },
}

/** 敏感度元数据 */
export const SENSITIVITY_META: Record<SensitivityLevel, {
  label: string
  color: string
  score: number
}> = {
  public: { label: '公开', color: '#2ecc71', score: 0 },
  internal: { label: '内部', color: '#3498db', score: 20 },
  sensitive: { label: '敏感', color: '#f39c12', score: 50 },
  confidential: { label: '机密', color: '#e67e22', score: 75 },
  critical: { label: '关键', color: '#e74c3c', score: 100 },
}

/** 暴露面状态元数据 */
export const EXPOSURE_STATUS_META: Record<ExposureStatus, {
  label: string
  color: string
  icon: string
}> = {
  safe: { label: '安全', color: '#2ecc71', icon: '🟢' },
  monitored: { label: '监控中', color: '#3498db', icon: '🔵' },
  exposed: { label: '已暴露', color: '#f39c12', icon: '🟡' },
  at_risk: { label: '有风险', color: '#e67e22', icon: '🟠' },
  breached: { label: '已泄露', color: '#e74c3c', icon: '🔴' },
}

// ============================================================
// 存储键
// ============================================================

const STORAGE_KEYS = {
  EXPOSURES: 'hf:privacy:exposures',
  PERMISSIONS: 'hf:privacy:permissions',
  AUDITS: 'hf:privacy:audits',
  SCORES: 'hf:privacy:scores',
  WARNINGS: 'hf:privacy:warnings',
  LOCK_STATE: 'hf:privacy:lock_state',
  CONFIG: 'hf:privacy:config',
} as const

// ============================================================
// 默认配置
// ============================================================

export const DEFAULT_PRIVACY_CONFIG: PrivacyDashboardConfig = {
  autoScoring: true,
  scoringInterval: 7,
  leakWarningEnabled: true,
  warningSensitivity: 0.7,
  autoLockTimeout: 30,
  permissionAuditEnabled: true,
  dataRetentionDays: 365,
}

// ============================================================
// 工具函数
// ============================================================

function generateId(prefix: string): string {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`
}

function now(): string {
  return new Date().toISOString()
}

// ============================================================
// 隐私仪表盘 Composable
// ============================================================

export function usePrivacyDashboard() {
  // ---- 配置 ----
  const config = ref<PrivacyDashboardConfig>(loadConfig())

  function loadConfig(): PrivacyDashboardConfig {
    try {
      const saved = storage.getKV<PrivacyDashboardConfig>(STORAGE_KEYS.CONFIG, DEFAULT_PRIVACY_CONFIG)
      return { ...DEFAULT_PRIVACY_CONFIG, ...saved }
    } catch {
      return { ...DEFAULT_PRIVACY_CONFIG }
    }
  }

  function persistConfig() {
    storage.setKV(STORAGE_KEYS.CONFIG, config.value)
  }

  // ---- 数据暴露面 ----
  const exposures = ref<DataExposure[]>(loadExposures())

  function loadExposures(): DataExposure[] {
    try {
      return storage.getKV<DataExposure[]>(STORAGE_KEYS.EXPOSURES, [])
    } catch {
      return []
    }
  }

  function persistExposures() {
    storage.setKV(STORAGE_KEYS.EXPOSURES, exposures.value)
  }

  /** 初始化数据暴露面（基于实际数据扫描） */
  function initializeExposures(): void {
    const entries: DataExposure[] = []

    for (const [category, meta] of Object.entries(DATA_CATEGORY_META)) {
      // 尝试从存储中估算数据量
      const estimatedCount = estimateDataCount(category as DataCategory)
      const estimatedSize = estimateDataSize(category as DataCategory)

      const exposureStatus = determineExposureStatus(
        category as DataCategory,
        estimatedCount,
        estimatedSize,
      )

      const riskScore = calculateExposureRisk(
        meta.defaultSensitivity,
        exposureStatus,
        estimatedCount,
      )

      entries.push({
        category: category as DataCategory,
        label: meta.label,
        description: meta.description,
        sensitivity: meta.defaultSensitivity,
        storageLocation: determineStorageLocation(category as DataCategory),
        encrypted: isDataEncrypted(category as DataCategory),
        estimatedCount,
        estimatedSize,
        exposureStatus,
        recentAccessCount: 0,
        lastAccessedAt: null,
        relatedModules: getRelatedModules(category as DataCategory),
        riskScore,
      })
    }

    exposures.value = entries
    persistExposures()
  }

  /** 更新暴露面条目 */
  function updateExposure(
    category: DataCategory,
    updates: Partial<DataExposure>,
  ): DataExposure | null {
    const idx = exposures.value.findIndex(e => e.category === category)
    if (idx < 0) return null

    exposures.value[idx] = {
      ...exposures.value[idx],
      ...updates,
      // 重新计算风险评分
      riskScore: calculateExposureRisk(
        updates.sensitivity ?? exposures.value[idx].sensitivity,
        updates.exposureStatus ?? exposures.value[idx].exposureStatus,
        updates.estimatedCount ?? exposures.value[idx].estimatedCount,
      ),
    }

    persistExposures()
    return exposures.value[idx]
  }

  /** 记录数据访问 */
  function recordAccess(category: DataCategory): void {
    const exposure = exposures.value.find(e => e.category === category)
    if (!exposure) return

    exposure.recentAccessCount++
    exposure.lastAccessedAt = now()
    persistExposures()
  }

  /** 获取暴露面摘要 */
  function getExposureSummary(): {
    totalCategories: number
    safeCategories: number
    atRiskCategories: number
    breachedCategories: number
    totalRiskScore: number
    highestRiskCategory: DataExposure | null
  } {
    const totalCategories = exposures.value.length
    const safeCategories = exposures.value.filter(e => e.exposureStatus === 'safe').length
    const atRiskCategories = exposures.value.filter(
      e => e.exposureStatus === 'at_risk' || e.exposureStatus === 'exposed',
    ).length
    const breachedCategories = exposures.value.filter(e => e.exposureStatus === 'breached').length
    const totalRiskScore = exposures.value.length > 0
      ? Math.round(exposures.value.reduce((sum, e) => sum + e.riskScore, 0) / exposures.value.length)
      : 0

    const sorted = [...exposures.value].sort((a, b) => b.riskScore - a.riskScore)
    const highestRiskCategory = sorted[0] || null

    return {
      totalCategories,
      safeCategories,
      atRiskCategories,
      breachedCategories,
      totalRiskScore,
      highestRiskCategory,
    }
  }

  // ---- 权限审计 ----
  const permissions = ref<PermissionEntry[]>(loadPermissions())
  const audits = ref<PermissionAudit[]>(loadAudits())

  function loadPermissions(): PermissionEntry[] {
    try {
      return storage.getKV<PermissionEntry[]>(STORAGE_KEYS.PERMISSIONS, [])
    } catch {
      return []
    }
  }

  function loadAudits(): PermissionAudit[] {
    try {
      return storage.getKV<PermissionAudit[]>(STORAGE_KEYS.AUDITS, [])
    } catch {
      return []
    }
  }

  function persistPermissions() {
    storage.setKV(STORAGE_KEYS.PERMISSIONS, permissions.value)
  }

  function persistAudits() {
    storage.setKV(STORAGE_KEYS.AUDITS, permissions.value)
  }

  /** 初始化默认权限条目 */
  function initializePermissions(): void {
    const defaultPermissions: PermissionEntry[] = [
      {
        id: generateId('perm'),
        name: '情绪数据读取',
        description: '读取情绪记录和波动历史',
        module: 'emotion',
        dataCategories: ['emotion'],
        level: 'read',
        granted: true,
        grantedAt: now(),
        grantedBy: 'system',
        revocable: false,
        lastUsedAt: null,
        riskLevel: 'low',
      },
      {
        id: generateId('perm'),
        name: '情绪数据写入',
        description: '创建和更新情绪记录',
        module: 'emotion',
        dataCategories: ['emotion'],
        level: 'write',
        granted: true,
        grantedAt: now(),
        grantedBy: 'system',
        revocable: false,
        lastUsedAt: null,
        riskLevel: 'low',
      },
      {
        id: generateId('perm'),
        name: '日记数据读取',
        description: '读取日记和笔记内容',
        module: 'diary',
        dataCategories: ['diary'],
        level: 'read',
        granted: true,
        grantedAt: now(),
        grantedBy: 'system',
        revocable: true,
        lastUsedAt: null,
        riskLevel: 'medium',
      },
      {
        id: generateId('perm'),
        name: '日记数据写入',
        description: '创建和编辑日记条目',
        module: 'diary',
        dataCategories: ['diary'],
        level: 'write',
        granted: true,
        grantedAt: now(),
        grantedBy: 'system',
        revocable: false,
        lastUsedAt: null,
        riskLevel: 'medium',
      },
      {
        id: generateId('perm'),
        name: '健康数据读取',
        description: '读取身心健康相关数据',
        module: 'health',
        dataCategories: ['health'],
        level: 'read',
        granted: true,
        grantedAt: now(),
        grantedBy: 'system',
        revocable: true,
        lastUsedAt: null,
        riskLevel: 'high',
      },
      {
        id: generateId('perm'),
        name: '位置数据读取',
        description: '读取地理位置记录',
        module: 'location',
        dataCategories: ['location'],
        level: 'read',
        granted: true,
        grantedAt: now(),
        grantedBy: 'system',
        revocable: true,
        lastUsedAt: null,
        riskLevel: 'high',
      },
      {
        id: generateId('perm'),
        name: '社交数据读取',
        description: '读取社交互动记录',
        module: 'social',
        dataCategories: ['social'],
        level: 'read',
        granted: true,
        grantedAt: now(),
        grantedBy: 'system',
        revocable: true,
        lastUsedAt: null,
        riskLevel: 'medium',
      },
      {
        id: generateId('perm'),
        name: '创作内容读取',
        description: '读取用户创作内容',
        module: 'creative',
        dataCategories: ['creative'],
        level: 'read',
        granted: true,
        grantedAt: now(),
        grantedBy: 'system',
        revocable: true,
        lastUsedAt: null,
        riskLevel: 'low',
      },
      {
        id: generateId('perm'),
        name: '系统配置管理',
        description: '读取和修改系统配置',
        module: 'system',
        dataCategories: ['system'],
        level: 'admin',
        granted: true,
        grantedAt: now(),
        grantedBy: 'system',
        revocable: false,
        lastUsedAt: null,
        riskLevel: 'high',
      },
      {
        id: generateId('perm'),
        name: '数据导出',
        description: '导出所有用户数据',
        module: 'export',
        dataCategories: ['emotion', 'diary', 'personal', 'behavior', 'health'],
        level: 'admin',
        granted: false,
        grantedAt: null,
        grantedBy: 'user',
        revocable: true,
        lastUsedAt: null,
        riskLevel: 'critical',
      },
      {
        id: generateId('perm'),
        name: '第三方集成',
        description: '允许第三方应用访问数据',
        module: 'integration',
        dataCategories: ['emotion', 'diary', 'personal'],
        level: 'read',
        granted: false,
        grantedAt: null,
        grantedBy: 'user',
        revocable: true,
        lastUsedAt: null,
        riskLevel: 'critical',
      },
      {
        id: generateId('perm'),
        name: '花园分享',
        description: '分享情绪花园给他人查看',
        module: 'emotion',
        dataCategories: ['emotion', 'creative'],
        level: 'read',
        granted: false,
        grantedAt: null,
        grantedBy: 'user',
        revocable: true,
        lastUsedAt: null,
        riskLevel: 'medium',
      },
    ]

    permissions.value = defaultPermissions
    persistPermissions()
  }

  /** 授予权限 */
  function grantPermission(permissionId: string): boolean {
    const perm = permissions.value.find(p => p.id === permissionId)
    if (!perm) return false

    perm.granted = true
    perm.grantedAt = now()
    persistPermissions()
    return true
  }

  /** 撤销权限 */
  function revokePermission(permissionId: string): boolean {
    const perm = permissions.value.find(p => p.id === permissionId)
    if (!perm || !perm.revocable) return false

    perm.granted = false
    perm.grantedAt = null
    persistPermissions()
    return true
  }

  /** 记录权限使用 */
  function recordPermissionUse(permissionId: string): void {
    const perm = permissions.value.find(p => p.id === permissionId)
    if (!perm || !perm.granted) return

    perm.lastUsedAt = now()
    persistPermissions()
  }

  /** 执行权限审计 */
  function performPermissionAudit(): PermissionAudit {
    const thirtyDaysAgo = new Date()
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30)

    const totalPermissions = permissions.value.length
    const grantedPermissions = permissions.value.filter(p => p.granted).length
    const highRiskPermissions = permissions.value.filter(
      p => p.granted && (p.riskLevel === 'high' || p.riskLevel === 'critical'),
    ).length

    const unusedPermissions = permissions.value.filter(p => {
      if (!p.granted) return false
      if (!p.lastUsedAt) return true
      return new Date(p.lastUsedAt) < thirtyDaysAgo
    }).length

    // 过度授权检测：权限级别超出实际需要
    const overGrantedPermissions = permissions.value.filter(p => {
      if (!p.granted) return false
      // 检测是否有 write 权限但从未写入
      if (p.level === 'write' || p.level === 'admin' || p.level === 'full') {
        return !p.lastUsedAt || new Date(p.lastUsedAt) < thirtyDaysAgo
      }
      return false
    }).length

    const recommendations: string[] = []

    if (unusedPermissions > 0) {
      recommendations.push(`发现 ${unusedPermissions} 个超过30天未使用的权限，建议审查并撤销`)
    }
    if (overGrantedPermissions > 2) {
      recommendations.push(`存在 ${overGrantedPermissions} 个过度授权，建议降级权限级别`)
    }
    if (highRiskPermissions > 3) {
      recommendations.push(`高风险权限数量(${highRiskPermissions})偏多，建议收紧权限策略`)
    }
    if (grantedPermissions > totalPermissions * 0.8) {
      recommendations.push('已授权权限占比较高，建议遵循最小权限原则')
    }

    const audit: PermissionAudit = {
      id: generateId('audit'),
      auditedAt: now(),
      totalPermissions,
      grantedPermissions,
      highRiskPermissions,
      unusedPermissions,
      overGrantedPermissions,
      permissions: [...permissions.value],
      recommendations,
    }

    audits.value = [audit, ...audits.value].slice(0, 50)
    persistAudits()
    return audit
  }

  /** 获取最近审计报告 */
  function getLatestAudit(): PermissionAudit | null {
    return audits.value[0] || null
  }

  // ---- 隐私评分 ----
  const scores = ref<PrivacyScore[]>(loadScores())

  function loadScores(): PrivacyScore[] {
    try {
      return storage.getKV<PrivacyScore[]>(STORAGE_KEYS.SCORES, [])
    } catch {
      return []
    }
  }

  function persistScores() {
    storage.setKV(STORAGE_KEYS.SCORES, scores.value)
  }

  /** 计算隐私评分 */
  function calculatePrivacyScore(): PrivacyScore {
    const now_ = now()

    // 维度 1: 数据加密保护 (25%)
    const encryptionItems = exposures.value.map(e => ({
      label: e.label,
      score: e.encrypted ? 100 : (e.sensitivity === 'critical' || e.sensitivity === 'confidential' ? 0 : 50),
      maxScore: 100,
      status: e.encrypted ? 'pass' as const : (e.sensitivity === 'critical' || e.sensitivity === 'confidential' ? 'fail' as const : 'warn' as const),
    }))
    const encryptionScore = encryptionItems.length > 0
      ? Math.round(encryptionItems.reduce((sum, i) => sum + i.score, 0) / encryptionItems.length)
      : 100

    // 维度 2: 暴露面控制 (25%)
    const exposureItems = exposures.value.map(e => ({
      label: e.label,
      score: e.exposureStatus === 'safe' ? 100
        : e.exposureStatus === 'monitored' ? 80
        : e.exposureStatus === 'exposed' ? 40
        : e.exposureStatus === 'at_risk' ? 20
        : 0,
      maxScore: 100,
      status: e.exposureStatus === 'safe' || e.exposureStatus === 'monitored' ? 'pass' as const
        : e.exposureStatus === 'exposed' ? 'warn' as const
        : 'fail' as const,
    }))
    const exposureScore = exposureItems.length > 0
      ? Math.round(exposureItems.reduce((sum, i) => sum + i.score, 0) / exposureItems.length)
      : 100

    // 维度 3: 权限管理 (25%)
    const grantedPerms = permissions.value.filter(p => p.granted)
    const highRiskGranted = grantedPerms.filter(p => p.riskLevel === 'high' || p.riskLevel === 'critical')
    const permScore = permissions.value.length > 0
      ? Math.round(Math.max(0, 100 - (highRiskGranted.length / permissions.value.length) * 40 - (grantedPerms.filter(p => !p.lastUsedAt).length / permissions.value.length) * 30))
      : 100

    const permissionItems = [
      {
        label: '已授权权限占比',
        score: permissions.value.length > 0 ? Math.round(100 - (grantedPerms.length / permissions.value.length) * 50) : 100,
        maxScore: 100,
        status: grantedPerms.length <= permissions.value.length * 0.5 ? 'pass' as const
          : grantedPerms.length <= permissions.value.length * 0.8 ? 'warn' as const
          : 'fail' as const,
      },
      {
        label: '高风险权限控制',
        score: Math.max(0, 100 - highRiskGranted.length * 20),
        maxScore: 100,
        status: highRiskGranted.length <= 2 ? 'pass' as const
          : highRiskGranted.length <= 4 ? 'warn' as const
          : 'fail' as const,
      },
      {
        label: '权限审计频率',
        score: audits.value.length > 0 ? 100 : 50,
        maxScore: 100,
        status: audits.value.length > 0 ? 'pass' as const : 'warn' as const,
      },
    ]

    // 维度 4: 泄露风险 (25%)
    const activeWarnings = warnings.value.filter(w => !w.resolved)
    const leakScore = Math.max(0, 100 - activeWarnings.length * 15 - activeWarnings.filter(w => w.level === 'high' || w.level === 'critical').length * 20)

    const leakItems = [
      {
        label: '活跃预警数',
        score: Math.max(0, 100 - activeWarnings.length * 20),
        maxScore: 100,
        status: activeWarnings.length === 0 ? 'pass' as const
          : activeWarnings.length <= 2 ? 'warn' as const
          : 'fail' as const,
      },
      {
        label: '一键锁定配置',
        score: config.value.autoLockTimeout > 0 ? 100 : 60,
        maxScore: 100,
        status: config.value.autoLockTimeout > 0 ? 'pass' as const : 'warn' as const,
      },
      {
        label: '数据保留策略',
        score: config.value.dataRetentionDays <= 365 ? 100 : 60,
        maxScore: 100,
        status: config.value.dataRetentionDays <= 365 ? 'pass' as const : 'warn' as const,
      },
    ]

    const dimensions: PrivacyScoreDimension[] = [
      { name: '数据加密保护', score: encryptionScore, weight: 25, items: encryptionItems },
      { name: '暴露面控制', score: exposureScore, weight: 25, items: exposureItems },
      { name: '权限管理', score: permScore, weight: 25, items: permissionItems },
      { name: '泄露风险', score: leakScore, weight: 25, items: leakItems },
    ]

    const total = Math.round(
      dimensions.reduce((sum, d) => sum + d.score * (d.weight / 100), 0),
    )

    let grade: PrivacyScore['grade'] = 'F'
    if (total >= 90) grade = 'A'
    else if (total >= 75) grade = 'B'
    else if (total >= 60) grade = 'C'
    else if (total >= 40) grade = 'D'

    // 趋势判断
    const previousScore = scores.value[0]
    let trend: PrivacyScore['trend'] = 'stable'
    let delta = 0
    if (previousScore) {
      delta = total - previousScore.total
      if (delta > 5) trend = 'improving'
      else if (delta < -5) trend = 'declining'
    }

    const score: PrivacyScore = {
      total,
      grade,
      dimensions,
      scoredAt: now_,
      trend,
      delta,
    }

    scores.value = [score, ...scores.value].slice(0, 52) // 保留一年
    persistScores()
    return score
  }

  /** 获取最新隐私评分 */
  function getLatestScore(): PrivacyScore | null {
    return scores.value[0] || null
  }

  // ---- 泄露预警 ----
  const warnings = ref<LeakWarning[]>(loadWarnings())

  function loadWarnings(): LeakWarning[] {
    try {
      return storage.getKV<LeakWarning[]>(STORAGE_KEYS.WARNINGS, [])
    } catch {
      return []
    }
  }

  function persistWarnings() {
    storage.setKV(STORAGE_KEYS.WARNINGS, warnings.value)
  }

  /** 生成泄露预警 */
  function generateWarning(
    level: ThreatLevel,
    title: string,
    description: string,
    affectedCategories: DataCategory[],
    probability: number,
    impact: LeakWarning['impact'],
    recommendations: string[],
  ): LeakWarning {
    const warning: LeakWarning = {
      id: generateId('leak_warn'),
      level,
      title,
      description,
      affectedCategories,
      probability,
      impact,
      recommendations,
      warnedAt: now(),
      acknowledged: false,
      resolved: false,
      autoGenerated: true,
    }

    warnings.value = [warning, ...warnings.value].slice(0, 100)
    persistWarnings()
    return warning
  }

  /** 运行泄露检测 */
  function runLeakDetection(): LeakWarning[] {
    if (!config.value.leakWarningEnabled) return []

    const newWarnings: LeakWarning[] = []
    const sensitivity = config.value.warningSensitivity

    // 检测规则 1: 未加密的敏感数据
    const unencryptedSensitive = exposures.value.filter(
      e => !e.encrypted && (e.sensitivity === 'critical' || e.sensitivity === 'confidential'),
    )
    if (unencryptedSensitive.length > 0 && sensitivity >= 0.5) {
      newWarnings.push(generateWarning(
        'high',
        '未加密的敏感数据',
        `发现 ${unencryptedSensitive.length} 类敏感数据未加密存储：${unencryptedSensitive.map(e => e.label).join('、')}`,
        unencryptedSensitive.map(e => e.category),
        0.8,
        'significant',
        ['立即启用数据加密', '审查存储位置安全性', '考虑迁移到加密存储'],
      ))
    }

    // 检测规则 2: 高风险权限过多
    const highRiskGranted = permissions.value.filter(
      p => p.granted && (p.riskLevel === 'high' || p.riskLevel === 'critical'),
    )
    if (highRiskGranted.length > 3 && sensitivity >= 0.6) {
      newWarnings.push(generateWarning(
        'medium',
        '高风险权限数量偏多',
        `当前有 ${highRiskGranted.length} 个高风险权限已授权，超出建议范围`,
        ['personal', 'system'],
        0.5,
        'moderate',
        ['审查并撤销不必要的高风险权限', '遵循最小权限原则', '定期执行权限审计'],
      ))
    }

    // 检测规则 3: 数据暴露面异常
    const atRiskExposures = exposures.value.filter(
      e => e.exposureStatus === 'at_risk' || e.exposureStatus === 'breached',
    )
    if (atRiskExposures.length > 0 && sensitivity >= 0.4) {
      newWarnings.push(generateWarning(
        atRiskExposures.some(e => e.exposureStatus === 'breached') ? 'critical' : 'high',
        '数据暴露面异常',
        `发现 ${atRiskExposures.length} 类数据处于风险暴露状态：${atRiskExposures.map(e => e.label).join('、')}`,
        atRiskExposures.map(e => e.category),
        atRiskExposures.some(e => e.exposureStatus === 'breached') ? 0.9 : 0.7,
        'significant',
        ['立即锁定受影响数据', '调查泄露来源', '通知受影响用户', '修复安全漏洞'],
      ))
    }

    // 检测规则 4: 大量数据集中存储
    const highVolumeExposures = exposures.value.filter(e => e.estimatedCount > 1000)
    if (highVolumeExposures.length > 3 && sensitivity >= 0.3) {
      newWarnings.push(generateWarning(
        'low',
        '大量数据集中存储',
        `${highVolumeExposures.length} 类数据量超过 1000 条，建议定期清理`,
        highVolumeExposures.map(e => e.category),
        0.3,
        'minimal',
        ['配置数据保留策略', '定期清理过期数据', '考虑数据归档'],
      ))
    }

    return newWarnings
  }

  /** 确认预警 */
  function acknowledgeWarning(warningId: string): boolean {
    const warning = warnings.value.find(w => w.id === warningId)
    if (!warning) return false

    warning.acknowledged = true
    persistWarnings()
    return true
  }

  /** 解决预警 */
  function resolveWarning(warningId: string): boolean {
    const warning = warnings.value.find(w => w.id === warningId)
    if (!warning) return false

    warning.resolved = true
    warning.acknowledged = true
    persistWarnings()
    return true
  }

  /** 获取活跃预警 */
  function getActiveWarnings(): LeakWarning[] {
    return warnings.value.filter(w => !w.resolved)
  }

  // ---- 一键锁定 ----
  const lockState = ref<LockState>(loadLockState())

  function loadLockState(): LockState {
    try {
      return storage.getKV<LockState>(STORAGE_KEYS.LOCK_STATE, {
        locked: false,
        lockedAt: null,
        reason: '',
        scope: 'all',
        duration: 0,
        expiresAt: null,
        unlockMethod: 'password',
        lockedBy: '',
      })
    } catch {
      return {
        locked: false,
        lockedAt: null,
        reason: '',
        scope: 'all',
        duration: 0,
        expiresAt: null,
        unlockMethod: 'password',
        lockedBy: '',
      }
    }
  }

  function persistLockState() {
    storage.setKV(STORAGE_KEYS.LOCK_STATE, lockState.value)
  }

  /** 一键锁定 */
  function lock(
    scope: LockState['scope'] = 'all',
    duration: number = 0,
    reason: string = '用户手动锁定',
  ): boolean {
    if (lockState.value.locked) return false

    const now_ = now()
    const expiresAt = duration > 0
      ? new Date(Date.now() + duration * 60000).toISOString()
      : null

    lockState.value = {
      locked: true,
      lockedAt: now_,
      reason,
      scope,
      duration,
      expiresAt,
      unlockMethod: duration > 0 ? 'timeout' : 'password',
      lockedBy: 'user',
    }

    // 锁定操作：撤销所有高风险权限
    if (scope === 'all' || scope === 'sensitive_only') {
      for (const perm of permissions.value) {
        if (perm.riskLevel === 'high' || perm.riskLevel === 'critical') {
          if (perm.revocable) {
            perm.granted = false
          }
        }
      }
      persistPermissions()
    }

    persistLockState()
    return true
  }

  /** 解锁 */
  function unlock(password?: string): boolean {
    if (!lockState.value.locked) return false

    // 检查密码
    if (lockState.value.unlockMethod === 'password') {
      if (config.value.lockPassword && password !== config.value.lockPassword) {
        return false
      }
    }

    // 检查超时
    if (lockState.value.unlockMethod === 'timeout') {
      if (lockState.value.expiresAt && new Date(lockState.value.expiresAt) > new Date()) {
        return false // 还没到解锁时间
      }
    }

    lockState.value = {
      locked: false,
      lockedAt: null,
      reason: '',
      scope: 'all',
      duration: 0,
      expiresAt: null,
      unlockMethod: 'password',
      lockedBy: '',
    }

    persistLockState()
    return true
  }

  /** 检查是否过期自动解锁 */
  function checkAutoUnlock(): boolean {
    if (!lockState.value.locked) return false
    if (lockState.value.unlockMethod !== 'timeout') return false
    if (!lockState.value.expiresAt) return false

    if (new Date(lockState.value.expiresAt) <= new Date()) {
      return unlock()
    }
    return false
  }

  /** 设置锁定密码 */
  function setLockPassword(password: string): void {
    config.value.lockPassword = password
    persistConfig()
  }

  // ---- 综合仪表盘 ----

  /** 获取完整隐私仪表盘数据 */
  function getDashboard(): {
    exposureSummary: ReturnType<typeof getExposureSummary>
    latestAudit: PermissionAudit | null
    latestScore: PrivacyScore | null
    activeWarnings: LeakWarning[]
    lockState: LockState
    overallStatus: 'safe' | 'warning' | 'danger'
  } {
    const exposureSummary = getExposureSummary()
    const latestAudit = getLatestAudit()
    const latestScore = getLatestScore()
    const activeWarnings = getActiveWarnings()

    let overallStatus: 'safe' | 'warning' | 'danger' = 'safe'
    if (activeWarnings.some(w => w.level === 'critical')) {
      overallStatus = 'danger'
    } else if (
      activeWarnings.some(w => w.level === 'high') ||
      exposureSummary.breachedCategories > 0 ||
      (latestScore && latestScore.total < 60)
    ) {
      overallStatus = 'warning'
    }

    return {
      exposureSummary,
      latestAudit,
      latestScore,
      activeWarnings,
      lockState: lockState.value,
      overallStatus,
    }
  }

  // ---- 初始化 ----
  if (exposures.value.length === 0) {
    initializeExposures()
  }
  if (permissions.value.length === 0) {
    initializePermissions()
  }

  // 定时检查自动解锁
  setInterval(() => {
    checkAutoUnlock()
  }, 30000)

  return {
    // 配置
    config,
    updateConfig: (partial: Partial<PrivacyDashboardConfig>) => {
      config.value = { ...config.value, ...partial }
      persistConfig()
    },

    // 数据暴露面
    exposures: computed(() => exposures.value),
    initializeExposures,
    updateExposure,
    recordAccess,
    getExposureSummary,

    // 权限审计
    permissions: computed(() => permissions.value),
    audits: computed(() => audits.value),
    initializePermissions,
    grantPermission,
    revokePermission,
    recordPermissionUse,
    performPermissionAudit,
    getLatestAudit,

    // 隐私评分
    scores: computed(() => scores.value),
    calculatePrivacyScore,
    getLatestScore,

    // 泄露预警
    warnings: computed(() => warnings.value),
    generateWarning,
    runLeakDetection,
    acknowledgeWarning,
    resolveWarning,
    getActiveWarnings,

    // 一键锁定
    lockState: computed(() => lockState.value),
    lock,
    unlock,
    checkAutoUnlock,
    setLockPassword,

    // 综合仪表盘
    getDashboard,
  }
}

// ============================================================
// 辅助函数
// ============================================================

/** 估算数据量 */
function estimateDataCount(category: DataCategory): number {
  const storageKeys: Partial<Record<DataCategory, string>> = {
    emotion: 'hf:emotion_records',
    diary: 'hf:diary_entries',
    personal: 'hf:user_profile',
    health: 'hf:health_data',
    system: 'hf:safety_config',
  }

  const key = storageKeys[category]
  if (!key) return 0

  try {
    const data = localStorage.getItem(key)
    if (!data) return 0
    const parsed = JSON.parse(data)
    if (Array.isArray(parsed)) return parsed.length
    return 1
  } catch {
    return 0
  }
}

/** 估算数据大小 */
function estimateDataSize(category: DataCategory): number {
  const storageKeys: Partial<Record<DataCategory, string>> = {
    emotion: 'hf:emotion_records',
    diary: 'hf:diary_entries',
    personal: 'hf:user_profile',
    health: 'hf:health_data',
    system: 'hf:safety_config',
  }

  const key = storageKeys[category]
  if (!key) return 0

  try {
    const data = localStorage.getItem(key)
    if (!data) return 0
    return new Blob([data]).size
  } catch {
    return 0
  }
}

/** 判断存储位置 */
function determineStorageLocation(category: DataCategory): StorageLocation {
  // 敏感数据默认加密本地存储
  const sensitiveCategories: DataCategory[] = ['emotion', 'diary', 'personal', 'health', 'financial']
  if (sensitiveCategories.includes(category)) return 'encrypted_local'
  return 'local'
}

/** 判断数据是否加密 */
function isDataEncrypted(category: DataCategory): boolean {
  const encryptedCategories: DataCategory[] = ['emotion', 'diary', 'personal', 'health', 'financial']
  return encryptedCategories.includes(category)
}

/** 判断暴露面状态 */
function determineExposureStatus(
  category: DataCategory,
  count: number,
  _size: number,
): ExposureStatus {
  // 无数据
  if (count === 0) return 'safe'

  // 健康的敏感数据需要加密
  if (['emotion', 'diary', 'personal', 'health'].includes(category)) {
    return isDataEncrypted(category) ? 'monitored' : 'exposed'
  }

  // 大容量数据需要监控
  if (count > 500) return 'monitored'

  return 'safe'
}

/** 计算暴露面风险评分 */
function calculateExposureRisk(
  sensitivity: SensitivityLevel,
  status: ExposureStatus,
  _count: number,
): number {
  const sensitivityScore = SENSITIVITY_META[sensitivity].score
  const statusMultiplier = status === 'safe' ? 0.5
    : status === 'monitored' ? 0.7
    : status === 'exposed' ? 1.0
    : status === 'at_risk' ? 1.3
    : 1.5

  return Math.min(100, Math.round(sensitivityScore * statusMultiplier))
}

/** 获取关联模块 */
function getRelatedModules(category: DataCategory): string[] {
  const moduleMap: Record<DataCategory, string[]> = {
    emotion: ['emotion', 'timeline', 'garden'],
    diary: ['diary', 'mirror', 'timeline'],
    personal: ['profile', 'settings', 'sanctuary'],
    behavior: ['analytics', 'timeline', 'worklog'],
    health: ['health', 'emotion', 'sanctuary'],
    location: ['location', 'timeline'],
    social: ['social', 'share', 'garden'],
    system: ['settings', 'safety', 'sanctuary'],
    creative: ['creative', 'output', 'canvas'],
    financial: ['finance', 'reward'],
  }
  return moduleMap[category] || []
}